##
##  Makefile -- Build procedure for sample mod_session_header Apache module
##  Autogenerated via ``apxs -n mod_session_header -g''.
##

builddir=.
top_srcdir=/usr/share/apache2/
top_builddir=/usr/share/apache2/
include /usr/share/apache2/build/special.mk

#   the used tools
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_session_header.o mod_session_header.lo mod_session_header.slo mod_session_header.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/mod_session_header

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

